export const ActionTypes = {
  GET_PHOTOS: 'GET_PHOTOS',
  GET_PHOTOS_SUCCESS: 'GET_PHOTOS_SUCCESS',
  
  GET_SELECTED_PHOTO: 'GET_SELECTED_PHOTO',
  GET_SELECTED_PHOTO_SUCCESS: 'GET_SELECTED_PHOTO_SUCCESS',
}
